### ISSUE TITLE
UnknownTaskException: Task with name 'check' not found

### ISSUE THREAD

**Issue by mvysny** [vlsi/vlsi-release-plugins#40] opened 2021-01-21 12:11 UTC
Hi, thank you for creating the Jandex plugin. However unfortunately I am unable to use it in my project. Having `build.gradle.kts` of

```kotlin
plugins {
    java
    id("com.github.vlsi.jandex") version "1.72"
}
```

and Gradle 6.7.1, the build fails with:

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'check' not found in root project 'vaadin-jandex'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:360)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:112)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:368)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:117)
        at com.github.vlsi.jandex.JandexPlugin.apply(JandexPlugin.kt:47)
        at com.github.vlsi.jandex.JandexPlugin.apply(JandexPlugin.kt:28)
```

**Comment by vlsi** [comment] 2021-02-08 20:14
Thanks for the report, the issue is fixed in 1.73

**Closed by vlsi** 2021-02-08 20:14 UTC
